// Code generated by "stringer -type=CustomerStatus"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CustomerInactive-0]
	_ = x[CustomerActive-1]
	_ = x[endCustomerStatus-2]
}

const _CustomerStatus_name = "CustomerInactiveCustomerActiveendCustomerStatus"

var _CustomerStatus_index = [...]uint8{0, 16, 30, 47}

func (i CustomerStatus) String() string {
	if i >= CustomerStatus(len(_CustomerStatus_index)-1) {
		return "CustomerStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CustomerStatus_name[_CustomerStatus_index[i]:_CustomerStatus_index[i+1]]
}
